[global]
domainNumber 0
network_transport UDPv4
delay_mechanism E2E
time_stamping hardware
uds_address /run/robotics-time/ptp4l
uds_file_mode 0660
uds_ro_address /run/robotics-time/ptp4lro
uds_ro_file_mode 0660
