---
moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
trajectory_execution:
  allowed_execution_duration_scaling: 1.5
  allowed_goal_duration_margin: 0.5
  allowed_start_tolerance: 0.02
  execution_duration_monitoring: true

moveit_simple_controller_manager:
  controller_names:
    - joint_trajectory_controller
  joint_trajectory_controller:
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - slider_joint
