#!/usr/bin/env python3
"""Derive foundation build inputs from one immutable workspace revision."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tomllib
from hashlib import sha256
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[3]
PACKAGES = {
    "contracts": "robotics-runtime-contracts",
    "harness": "robotics-acceptance-harness",
}


def git(workspace: Path, *args: str) -> bytes:
    return subprocess.check_output(
        ["git", "-C", str(workspace), *args], stderr=subprocess.PIPE
    )


def workspace_pin(root: Path) -> dict[str, str]:
    # JSON is also valid YAML for vcs2l's .repos format.
    manifest = json.loads((root / "foundation.repos").read_text(encoding="utf-8"))
    repositories = manifest["repositories"]
    if set(repositories) != {"robotics-runtime"}:
        raise ValueError(
            "foundation.repos must contain exactly the robotics-runtime workspace"
        )
    pin = repositories["robotics-runtime"]
    identities = json.loads(
        (root / "config/trust/identities.json").read_text(encoding="utf-8")
    )
    expected_url = f"https://github.com/{identities['core']['repository']}.git"
    if pin.get("type") != "git" or pin.get("url") != expected_url:
        raise ValueError("foundation source must match the configured core repository")
    if not re.fullmatch(r"[a-f0-9]{40}", pin.get("version", "")):
        raise ValueError("foundation version must be an immutable full Git commit")
    return pin


def requirements(project: dict[str, Any]) -> list[str]:
    result = []
    for value in project["dependencies"]:
        match = re.match(r"[A-Za-z0-9][A-Za-z0-9._-]*", value)
        if match is None:
            raise ValueError(f"invalid dependency name: {value!r}")
        name = re.sub(r"[-_.]+", "-", match.group()).lower()
        if name not in PACKAGES.values():
            result.append(value)
    return result


def requirement_text(values: list[str]) -> str:
    return (
        "# Generated by scripts/ci/foundation/sync-workspace-pins.py\n"
        + "\n".join(sorted(set(values), key=str.lower))
        + "\n"
    )


def export_lock(workspace: Path, revision: str, distribution: str) -> str:
    if git(workspace, "rev-parse", "HEAD").decode().strip() != revision:
        raise ValueError(
            "uv export requires the imported workspace at the pinned revision"
        )
    git(
        workspace,
        "diff",
        "--quiet",
        "HEAD",
        "--",
        "pyproject.toml",
        "uv.lock",
        "packages",
    )
    return (
        subprocess.check_output(
            [
                "uv",
                "export",
                "--project",
                str(workspace),
                "--locked",
                "--no-default-groups",
                "--package",
                distribution,
                "--no-emit-workspace",
                "--no-header",
                "--no-annotate",
                "--format",
                "requirements.txt",
            ],
            stderr=subprocess.PIPE,
        )
        .decode()
        .replace("\r\n", "\n")
    )


def export_build_lock(root: Path, values: list[str], *, refresh: bool) -> str:
    command = [
        "uv",
        "pip",
        "compile",
        "-",
        "--python-version",
        "3.12",
        "--universal",
        "--generate-hashes",
        "--no-header",
        "--no-annotate",
    ]
    existing = root / "docker/python/foundation-build.lock"
    if existing.exists() and not refresh:
        command.extend(["--constraint", str(existing)])
    result = subprocess.run(
        command,
        input=requirement_text(values).encode(),
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=True,
    )
    return result.stdout.decode().replace("\r\n", "\n")


def outputs(
    root: Path, workspace: Path, *, refresh_build_lock: bool = False
) -> dict[Path, str]:
    pin = workspace_pin(root)
    revision = pin["version"]
    actual = git(workspace, "rev-parse", f"{revision}^{{commit}}").decode().strip()
    if actual != revision:
        raise ValueError("workspace revision did not resolve to the pinned commit")
    lock_bytes = git(workspace, "show", f"{revision}:uv.lock")
    lock = tomllib.loads(lock_bytes.decode())
    metadata = {}
    packages = {}
    for directory, distribution in PACKAGES.items():
        path = f"packages/{directory}"
        data = tomllib.loads(
            git(workspace, "show", f"{revision}:{path}/pyproject.toml").decode()
        )
        project = data["project"]
        if project["name"] != distribution:
            raise ValueError(f"unexpected distribution in {path}")
        matches = [p for p in lock["package"] if p["name"] == distribution]
        if len(matches) != 1 or matches[0]["version"] != project["version"]:
            raise ValueError(f"workspace lock disagrees with {distribution} metadata")
        if matches[0]["source"] != {"editable": path}:
            raise ValueError(f"workspace lock does not bind {distribution} to {path}")
        packages[directory] = {
            "distribution": distribution,
            "version": project["version"],
            "path": path,
            "git_tree": git(workspace, "rev-parse", f"{revision}:{path}")
            .decode()
            .strip(),
        }
        metadata[directory] = data
    epoch = git(workspace, "show", "-s", "--format=%ct", revision).decode().strip()
    source = f"{pin['url']}?ref={revision}&checksum={revision}"
    foundation = {
        "workspace": {
            "url": pin["url"],
            "revision": revision,
            "source_date_epoch": int(epoch),
            "uv_lock_sha256": sha256(lock_bytes).hexdigest(),
        },
        "packages": packages,
    }
    contracts_dependencies = requirements(metadata["contracts"]["project"])
    harness_dependencies = requirements(metadata["harness"]["project"])
    build_dependencies = [
        r for data in metadata.values() for r in data["build-system"]["requires"]
    ]
    bake_path = root / "docker-bake.hcl"
    bake = bake_path.read_text(encoding="utf-8")
    begin, end = "# FOUNDATION_GENERATED_START", "# FOUNDATION_GENERATED_END"
    if bake.count(begin) != 1 or bake.count(end) != 1:
        raise ValueError(
            "Docker Bake must contain exactly one generated foundation block"
        )
    replacement = (
        f'{begin}\nvariable "FOUNDATION_SOURCE" {{\n  default = "{source}"\n}}\n{end}'
    )
    start, stop = bake.index(begin), bake.index(end) + len(end)
    rows = [
        "# Foundation Compatibility Lock",
        "",
        "Generated from the single workspace revision in `foundation.repos`.",
        "",
        "| Component | Version | Workspace commit |",
        "| --- | --- | --- |",
        *[
            f"| `{p['distribution']}` | `{p['version']}` | `{revision}` |"
            for p in packages.values()
        ],
        "",
        "The current pin is a development candidate, not a published release pair.",
        "Both packages are built from this source with locked build dependencies.",
        "CI checks the imported revision, workspace lock and installed image versions.",
        "Stable release adoption remains gated on publication and foundation qualification.",
        "",
    ]
    return {
        root / "config/foundation-lock.json": json.dumps(foundation, indent=2) + "\n",
        root / "docker/python/acceptance-observer.in": requirement_text(
            contracts_dependencies + harness_dependencies
        ),
        root / "docker/python/permit-preflight.in": requirement_text(
            contracts_dependencies
        ),
        root / "docker/python/acceptance-observer.lock": export_lock(
            workspace, revision, PACKAGES["harness"]
        ),
        root / "docker/python/permit-preflight.lock": export_lock(
            workspace, revision, PACKAGES["contracts"]
        ),
        root / "docker/python/foundation-build.in": requirement_text(
            build_dependencies
        ),
        root / "docker/python/foundation-build.lock": export_build_lock(
            root, build_dependencies, refresh=refresh_build_lock
        ),
        root / "docs/foundation-compatibility.md": "\n".join(rows),
        bake_path: bake[:start] + replacement + bake[stop:],
    }


def synchronize(
    root: Path, workspace: Path, *, check: bool, refresh_build_lock: bool = False
) -> None:
    expected = outputs(root, workspace, refresh_build_lock=refresh_build_lock)
    mismatches = [
        p
        for p, content in expected.items()
        if not p.exists() or p.read_bytes() != content.encode()
    ]
    if check and mismatches:
        raise ValueError(
            "stale foundation inputs: "
            + ", ".join(str(p.relative_to(root)) for p in mismatches)
        )
    for path in mismatches:
        path.parent.mkdir(parents=True, exist_ok=True)
        temporary = path.with_name(path.name + ".tmp")
        temporary.write_text(expected[path], encoding="utf-8", newline="\n")
        temporary.replace(path)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--workspace", type=Path, default=ROOT / "dependencies/robotics-runtime"
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--refresh-build-lock", action="store_true")
    mode.add_argument("--revision", action="store_true")
    args = parser.parse_args()
    try:
        if args.revision:
            sys.stdout.buffer.write((workspace_pin(ROOT)["version"] + "\n").encode())
        else:
            synchronize(
                ROOT,
                args.workspace,
                check=args.check,
                refresh_build_lock=args.refresh_build_lock,
            )
    except (OSError, ValueError, KeyError, subprocess.CalledProcessError) as exc:
        parser.exit(1, f"foundation pins: {exc}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
